### PR TITLE
Video based on PyQt [IN PROGRESS]

### PR DESCRIPTION
**Pull request by swarmer**
Terminal window based on PyQt, works in Py3k too.
Based on `jtauber:video`.
- No color
- Hardcoded size (will likely be screwed for everybody except me)
- Didn't remove pygame-based code (yet).

### CODE REVIEW

**Comment by jtauber** [comment]
i could even add a NullTerminal which would enable parity with master

**Comment by jtauber** [comment]
@swarmer let me know if you're okay with my new API (or think I should make further changes). Goal is to have identical dcpu16.py regardless of Qt vs pygame vs whatever.

**Comment by jtauber** [comment]
sorry, you'll need to merge back master changes now, @swarmer but it will actually make the difference less

**Comment by swarmer** [comment]
@jtauber Looks fine.

**Comment by swarmer** [comment]
I'll try to rebase my branch then.

**Pull request closed without merging**
