### PR TITLE
Qt-based terminal [IN PROGRESS]

### PR DESCRIPTION
**Pull request by swarmer**
Needs:
- ~~Testing (on various platforms)~~
- ~~Size calculated at runtime based on font~~
- Stop emulator when terminal is closed

### CODE REVIEW

**Comment by jtauber** [comment]
now that terminals are orthogonal to everything else, I'm happy to merge this in as is and just improve it from master. What do you think, @swarmer ?

**Comment by swarmer** [comment]
The problem is I have to create pull request every time I want to push code in your repo.

**Comment by jtauber** [comment]
what if I reopen after each merge?

**Comment by swarmer** [comment]
Ok, merge it.

**Comment by jtauber** [comment]
I guess I can't reopen :/

**Pull request merged**
