### PR TITLE
Use absolute path for terminal directory

### PR DESCRIPTION
**Pull request by sebastianw**
This way the terminals can be loaded even if dcpu16.py is started
from another directory.

### CODE REVIEW

**Comment by andre-d** [comment]
Sorry about that, was thinking I got that when I did the change for plugins.  Forgot to actually do that.

**Comment by jtauber** [comment]
wouldn't it be better to use os.path.join rather than + ?

**Comment by sebastianw** [comment]
Yes probably, then you would have to get rid of all the slashes. And somehow now everything I add on my master branch is showing up in this pull request. :(

**Comment by sebastianw** [comment]
I'll do a new pull request as soon as I have figured out how to only do a pull request for one commit...

**Comment by andre-d** [comment]
You need to make a branch with only that commit, and pull request that branch

**Comment by sebastianw** [comment]
yeah, figured it out. ;)

**Pull request closed without merging**
