### PR TITLE
Added support for audio output system of the series DCP-16f series chip

### PR DESCRIPTION
**Pull request by FarMcKon**
Added first draft of code for Apple I style audio output via 2 channel audio register, using reserved instructions.   To keep backwards compatibility, the series f assembler and emulator are built into separate python files for now.

This work also included a tick counter for timing, for audio use later.

### CODE REVIEW

**Comment by andre-d** [comment]
You have "added examples as a submodule" and "updated subproject link to examples" as a commit in this pull request.   You will want to rebase those out.

**Comment by FarMcKon** [comment]
Well, in this case I have a (EXTREMELY SIMPLE) examples of audio output in my own examples repo not in the main repo, as well as in-examples documentation of the clone chip.   That rug really ties the room together. And by rug I mean 'examples' and by 'ties the room together' I mean 'makes my hacks testable/usable'

I'm guessing if someone digs my f series knock-off chip, please clone over the related docs and examples in Examples before grabbing the assembler and emulator. 

kthx bai!

**Comment by jtauber** [comment]
perhaps a different examples folder?

**Comment by FarMcKon** [comment]
sure. That is a good solution. I'll re-request.

**Pull request closed without merging**
