### PR TITLE
pyparsing based assembler and Spacing fix to example.asm

### PR DESCRIPTION
**Pull request by pwaller**
Just for the sake of interest, I implemented an assembler based on pyparsing. Thought you might be interested, though no issues if you don't want to merge.

I also just removed excess whitespace at the beginning of example.asm.

### CODE REVIEW

**Comment by swarmer** [comment]
It crashes for me on example.asm

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 387, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "asm_pyparsing.py", line 4, in <module>
    """
  File "asm_pyparsing.py", line 156, in main
    p = codegen(open("example.asm").read())
  File "asm_pyparsing.py", line 145, in codegen
    program[i] = labels[c]
KeyError: '0x30'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/anton/projects/dcpu16py/asm_pyparsing.py(145)codegen()
-> program[i] = labels[c]
(Pdb) pp labels
{'crash': 32, 'loop': 15, 'testsub': 29}
(Pdb) pp c
'0x30'
(Pdb) pp program
[31745,
 '0x30',
 32225,
 '0x1000',
 '0x20',
 30723,
 '0x1000',
 31757,
 '0x10',
 32193,
 'crash',
 31841,
 '10',
 31745,
 '0x2000',
 8545,
 '0x2000',
 31843,
 '1',
 31853,
 '0',
 32193,
 'loop',
 31793,
 '0x4',
 31760,
 'testsub',
 32193,
 'crash',
 31799,
 '4',
 25025,
 32193,
 'crash']
```

**Comment by pwaller** [comment]
Odd. What version of python and pyparsing are you using? You're using my unmodified master? Are you able to debug?

```
$ python -c "import pyparsing as P; print P.__version__"
1.5.5
```

**Comment by pwaller** [comment]
Ah, reproduced on pyparsing 1.5.6.

**Comment by pwaller** [comment]
I don't understand. `setParseAction` and `addParseAction` don't seem to be working for `hex_literal` and `dec_literal` in the newer version of pyparsing. It seems like a pyparsing bug, I can't see why it doesn't work.

**Comment by pwaller** [comment]
Fixed in latest master. Unfortunately, I don't understand why the position of those lines matters, but it works now.

**Comment by swarmer** [comment]
Parsing of

```
SET A, 42
SET B, 42
```

fails:

```
Match program at loc 0(1,1)
Match line at loc 0(1,1)
Match operand at loc 3(1,4)
Matched operand -> [['A']]
Match operand at loc 6(1,7)
Matched operand -> [[42]]
Exception raised:Expected lineEnd (at char 10), (line:2, col:1)
Exception raised:Expected lineEnd (at char 10), (line:2, col:1)
Traceback (most recent call last):
  File "asm_pyparsing.py", line 165, in <module>
    main()
  File "asm_pyparsing.py", line 160, in main
    p = codegen(open(sys.argv[1]).read())
  File "asm_pyparsing.py", line 114, in codegen
    parsed = full_grammar.parseString(source)
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1032, in parseString
    raise exc
pyparsing.ParseException: Expected lineEnd (at char 10), (line:2, col:1)
```

But

```
SET A, 42 ;comment
SET B, 42
```

works fine.

**Comment by swarmer** [comment]
I guess I have a patch to fix that:

```
From 6c5902d399f95a2f728e862ae57efdf3c60a7c60 Mon Sep 17 00:00:00 2001
From: Anton Barkovsky <swarmer.pm@gmail.com>
Date: Thu, 5 Apr 2012 18:53:26 +0300
Subject: [PATCH] Set \n not to be ignorable whitespace

---
 asm_pyparsing.py |    3 +++
 1 file changed, 3 insertions(+)

diff --git a/asm_pyparsing.py b/asm_pyparsing.py
index 3193530..79eb2f5 100755
--- a/asm_pyparsing.py
+++ b/asm_pyparsing.py
@@ -9,6 +9,9 @@ import os
 # Run with "DEBUG=1 python ./asm_pyparsing.py"
 DEBUG = "DEBUG" in os.environ

+# otherwise \n is also treated as ignorable whitespace
+P.ParserElement.setDefaultWhitespaceChars(' \t')
+
 identifier = P.Word(P.alphas+"_", P.alphanums+"_")
 label = P.Combine(P.Literal(":").suppress() + identifier)

-- 
1.7.9.4
```

**Comment by pwaller** [comment]
@swarmer: thanks for the patch, I included it in the new pull request #14.

**Pull request merged**
