### PR TITLE
Use argparse on assembler and disassembler

### PR DESCRIPTION
**Pull request by matze**
Unfortunately, this reverses the parameter order with asm.py but is more
consistent with the gcc interface.

### CODE REVIEW

**Comment by jtauber** [comment]
needs to be updated for merge

**Comment by matze** [comment]
Done. I also merged in some changes (matze/dcpu16py@9a09f38) that cleaned up asm.py a little bit and fixed errors concerning unknown identifiers. But if you don't like them you can leave them out.

**Comment by jtauber** [comment]
sorry, I did another merge first which messed this one up again.

Can you do a fresh pull request that doesn't have the merge commits?

**Comment by matze** [comment]
Alright, will open a new pull request.

**Pull request closed without merging**
