### PR TITLE
Moved terminals into their own folder and removed null terminal

### PR DESCRIPTION
**Pull request by andre-d**
I needed a convention to disable the terminal plugin all together.  Is there any reason we need a null terminal, but would want the terminal plugin enabled?

I have also moved terminals into their own folder

I also corrected how often we redraw the screen to be based on time instead of ticks

I also added a bold curses terminal to deal with some people not wanting bold curses

### CODE REVIEW

**Comment by swarmer** [comment]
BTW, how about moving all terminals into their own folder?

**Comment by andre-d** [comment]
./plugins/termals/ or ./terminals/?

**Comment by swarmer** [comment]
Terminals themselves aren't plugins so I'd move then into `./terminals`

**Comment by andre-d** [comment]
Done

**Comment by andre-d** [comment]
I also made the display update based on time instead of ticks, it was not updating often enough on one computer and too often on the other.

**Pull request merged**
