### PR TITLE
Added a plugin system [NEEDS WORK]

### PR DESCRIPTION
**Pull request by andre-d**
Still needs a decorator or something inside dcpu16 to watch for changes to a memory address which can be used within plugins.

Needs work to be synced with the tick one way or another, with threaded locking or calling all the plugins in order once per tick.

### CODE REVIEW

**Comment by andre-d** [comment]
Discussion regarding this in #9

**Comment by swarmer** [comment]
Maybe move that branch to @jtauber's repo and merge with master later, when this architecture is tested with at least 1 working plugin?

**Comment by jtauber** [comment]
how do we change the target of this pull request to a plugin branch on my side? just bypass github and add your repo as a remote and merge from andre-d/plugin to my plugin? not sure how github pull request will handle seeing that

**Comment by swarmer** [comment]
Close this pull request, add remote to andre-d, fetch his `plugin` branch, and push it to your repo, I think.

**Comment by jtauber** [comment]
@swarmer that's what I thought; hopefully he can then target pull requests to jtauber:plugin

**Comment by jtauber** [comment]
k, created a jtauber:plugin but note that andre-d:plugin needs to get master's latest changes

**Pull request closed without merging**
