### PR TITLE
added python 2.7 version

### PR DESCRIPTION
**Pull request by FarMcKon**
Please accept this, my patch. 

It's the minimum change to dcpu16 get the now 3.0 specific version to compile with my lowly python 2.7 laptop. This is done to extend the hackability of the magic.

### CODE REVIEW

**Comment by jtauber** [comment]
I don't understand this. I run the existing code on 2.7 all the time without problem.

**Comment by andre-d** [comment]
Are you sure you are not on 2.4 or something? (Far McKon)

**Comment by andre-d** [comment]
I am running it fine with 2.7, and it _should_ also run on 2.6 if I recall correctly.  

[user dcpu16py]$ python2 --version
Python 2.7.2

**Comment by andre-d** [comment]
http://docs.python.org/library/importlib.html is available in 2.7

and a third party version is available if you are in 2.6 http://pypi.python.org/pypi/importlib

edit: 
http://docs.python.org/library/argparse.html#module-argparse  as is argparse  available as http://pypi.python.org/pypi/argparse for older python versions

**Comment by enkore** [comment]
I also don't see the point here, as the code runs without any issues with Python 2.7 (to be precise, we actually develop this using 2.7) and it should also run without a problem with 3.x.

**Comment by jtauber** [comment]
I'm doing all my development on 2.7 without problem (occasionally testing on python3) so I'm just going to close this.

If @FarMcKon meant something other than 2.7, a new pull request can be opened.

**Comment by FarMcKon** [comment]
Nope, I can't run it on 2.7. I'll double check the libs I have installed on this machine. 

I get import errors on importlib and import errors on argparse. I have a mac that was 2.6 and upgraded to 2.7  I've had library problems before due to OSX 'wanting' 2.6 over my manual install of 2.7. 

Looks like a local issue then.. :(

**Comment by enkore** [comment]
Yeah, its definitefly a broken python installation on your side. Sounds a bit like your using a python2.7 binary which uses then the python2.6 Lib...

**Pull request closed without merging**
