### PR TITLE
Video

### PR DESCRIPTION
**Pull request by jtauber**
Just going to get something working with PyGame first although this will break Python3 and PyPy support at first.

### CODE REVIEW

**Comment by jtauber** [comment]
Note that the conversation in #9 can move here now

**Comment by jtauber** [comment]
note that I'm currently assuming Apple ][ screen dimensions and the code points in the character generator are all wrong for ASCII

but it displays something and it's a start :-)

**Comment by jtauber** [comment]
once I sort out the code points (and add lower-case characters) it should work great for `examples/hello.asm`

**Comment by jtauber** [comment]
Need to:
- establish what the screen pixel dimensions are (and implement that)
- establish what the character pixel dimensions are (and implement that)
- create an ascii-compatible glyph set
- implement colour support

**Comment by swarmer** [comment]
I'm now trying to implement 80x25 terminal in PyQt (which supports py3k).

**Comment by jtauber** [comment]
Do we know if it's definitely 80x25? My guess is it won't be that wide.

**Comment by swarmer** [comment]
No. It's my guess. Will adjust size later.

**Comment by jtauber** [comment]
working on lowercase letters now :-)

**Comment by jtauber** [comment]
which means examples/hello.asm works :-)

**Comment by jtauber** [comment]
with the null terminal done, I think I can merge this into master and just make the null terminal the default (for parity)

**Comment by jtauber** [comment]
Colour can wait until after merge :-)

**Pull request merged**
