### PR TITLE
Improve Qt terminal performance

### PR DESCRIPTION
**Pull request by swarmer**
On my machine, on hello2 - from 33kHz to ~120kHz.

### CODE REVIEW

**Comment by andre-d** [comment]
This makes a _lot_ of sense

**Comment by jtauber** [comment]
can this be updated for terminal move and I'll accept

**Comment by swarmer** [comment]
Merged.

**Comment by andre-d** [comment]
You wanted to rebase (moves your commit in front of the others), not merge (creates a commit applying those changes as your own in one commit) (Although it may still apply)

**Comment by swarmer** [comment]
Create new pull request only for cleaner history? :/

**Comment by andre-d** [comment]
You will need to git rebase interactive and remove the merge commit, then git rebase up to origin/master.  Or just make a new branch with a new pull request if you are not sure how to do that.

**Comment by swarmer** [comment]
Wait, you don't suggest me to rebase already pushed online branch?

**Comment by andre-d** [comment]
That was the first suggestion, just do whatever works :)

**Comment by andre-d** [comment]
Nevermind, he merged it in, worked fine, I guess rebasing it just gives it a cleaner commit history

**Pull request merged**
