### PR TITLE
Debugger [COMPLETE]

### PR DESCRIPTION
**Pull request by swarmer**
--debug mode now stops after every cycle and asks command from user.
Current debugger commands:
- g[et] addr
- g[et] %register
- s[et] addr value
- s[et] %register value
- help
- st[ep]
- break addr[...]
- c[ont[inue]]
- cl[ear] addr[...]
- `Ctrl-D` - exit

get is also aliased as p[rint], step as empty string.
Detailed info - `help` command.

### CODE REVIEW

**Comment by enkore** [comment]
I would propose to merge that with #28 - making this behaviour available with a seperate command line option.

**Comment by swarmer** [comment]
Command line options would be slightly confusing.
How about `--trace` to only print debugging info and `--debug` for my full-blown debugger?

**Comment by enkore** [comment]
Aggree :)

**Comment by jtauber** [comment]
Thanks for merging your work. I'll review (and hopefully merge) later today.

**Comment by swarmer** [comment]
I haven't finished yet! :)

**Comment by jtauber** [comment]
@swarmer shall we adopt the convention of using [IN PROGRESS] in the pull request title until you think it's ready?

**Comment by enkore** [comment]
Good idea, thus we can prevent double implementations.

**Comment by swarmer** [comment]
I hereby declare this pull request sort of finished.

**Pull request merged**
